import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
// import "react-toastify/dist/ReactToastify.css";
// import { ToastContainer } from 'react-toastify';

const outfit = Outfit({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "CashTrackr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
        {children}
        {/* <ToastContainer /> */}
      </body>
    </html>
  );
}